version: '3.8'
x-common:
   env_file: &id001
   - public.env
services:
   app:
      env_file: *id001
      environment:
      - APP_ENV=test
      build:
         context: .
      image: phenopolis_api
      command: |
         sh -c "gunicorn -b 0.0.0.0:5000 --reload --workers=1 --threads=15 application:application"
      ports:
      - 5000:5000
      volumes:
      - ./:/app
      depends_on:
      - db
   db:
      env_file: *id001
      image: postgres:12-alpine
      volumes:
      - db:/var/lib/postgresql/data
      - ./:/app
      - ./schema/initdb.d/:/docker-entrypoint-initdb.d
volumes:
   db: null
