# Used only in GitHub Workflow tests with "docker-compose -f dc_4_test.yml up -d"
# Lint with flake8:       "docker-compose -f dc_4_test.yml exec -T app flake8 -v --count"
# Check format with blac: "docker-compose -f dc_4_test.yml exec -T app black --diff --check ."
# Test with PyTest:       "docker-compose -f dc_4_test.yml exec -T app pytest --color=yes -k 'not test_variant'"

version: '3.8'
x-common: &common
   env_file:
   - public.env
services:
   app:
      <<: *common
      environment:
      - APP_ENV=test
      build:
         context: .
      image: phenopolis_api
      command: |
         sh -c "gunicorn -b 0.0.0.0:5000 --reload --workers=1 --threads=15 application:application"
      ports:
      - 5000:5000
      volumes:
      - ./:/app
      depends_on:
      - db
   db:
      <<: *common
      image: postgres:12-alpine
      volumes:
      - db:/var/lib/postgresql/data
      - ./:/app
      - ./schema/initdb.d/:/docker-entrypoint-initdb.d
volumes:
   db: null
