version: '3.8'
services:
   app:
      build:
         context: .
      image: phenopolis_api:base_dev
      command: sh -c "gunicorn -b 0.0.0.0:8000 --reload --workers=1 --threads=15 application:application"
      ports:
      - 8000:8000
      working_dir: /app
      volumes:
      - ./:/app
      env_file:
      - public.env
      - private.env
      expose:
      - 8000
      depends_on:
      - db
   db:
      image: postgres:12-alpine
      volumes:
      - ./:/app
      env_file:
      - public.env
      - private.env
