#   publish = "build"	
#   command = "npm run build"	


# [[redirects]]
#   from = "/api/*"	
#   to = "https://api-dev.phenopolis.org/:splat"	
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"}

[build]
  publish = "build"
  command = "npm run build"

[context.master]
  command = "npm run build; cp _redirects_dev build/_redirects"

[context.live]
  command = "npm run build; cp _redirects_live build/_redirects"
