[build]
  publish = "build"
  command = "npm run build"

[context.dev]
  command = "npm run build; cp _redirects_dev build/_redirects"

[context.live]
  command = "npm run build; cp _redirects_live build/_redirects"
