branch-defaults:
  ec2:
    environment: Phenopolis-api
  postgres:
    environment: Phenopolis-api
    group_suffix: null
global:
  application_name: phenopolis
  branch: null
  default_ec2_keyname: phenogenon
  default_platform: Python 3.6
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: phenopolis
  repository: null
  sc: git
  workspace_type: Application
