branch-defaults:
  prod-live:
    environment: Phenopolis-api-production-env
  dev-live:
    environment: Phenopolisapi-dev-env
environment-defaults:
  Phenopolis-api-production-env:
    branch: null
    repository: null
global:
  application_name: phenopolis
  default_ec2_keyname: phenopolis-api-bastion-server
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: phenopolis
  sc: git
  workspace_type: Application
