# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application
on:
   push:
      branches:
      - prod-live
   pull_request:
      branches:
      - prod-live
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  name: Set up Python 3.8
         uses: actions/setup-python@v2
         with:
           python-version: 3.8
      -  name: Install docker-compose-wait
         run: |
           python -m pip install --upgrade pip
           pip install docker-compose-wait
      -  name: Run docker-compose stack
         run: docker-compose up -d
      -  name: Run docker-compose-wait
         run: |
           docker-compose-wait
           # curl -f http://localhost:5000/check_health
      -  name: Lint with flake8
         run: docker-compose exec -T app flake8 -v --count
      -  name: Check format with black
         run: docker-compose exec -T app black --diff --check .
      -  name: Test with PyTest
         run: docker-compose exec -T app pytest --color=yes -k 'not test_variant'
