# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application
on:
   push:
      branches:
      - test_action
   pull_request:
      branches:
      - prod-live
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  name: Run docker-compose stack
         run: docker-compose -f docker-compose2.yml up -d
      -  name: Check folder
         run: pwd
      -  name: Check files
         run: ls -ltr
      -  name: Check running containers
         run: docker ps -a
      -  name: Check logs
         run: |
            docker logs workspace_app_1
            docker logs workspace_db_1
# if docker container app were running then... I wish I could run these...
      -  name: Lint with flake8
         run: docker-compose exec app flake8
      -  name: Check format with black
         run: docker-compose exec app black --diff --check .
      -  name: Test with PyTest
         run: docker-compose exec app pytest
